site_name: 从零开始掌握 PyTorch 深度学习
site_url: https://eanyang7.github.io/pytorch/
site_description: 欢迎来到互联网上最适合初学者学习 PyTorch 深度学习的地方。
site_author: Ean Yang

repo_url: https://github.com/EanYang7/pytorch
repo_name: github仓库

theme:
  language: zh
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye
  palette:
    # 可选颜色见https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
    # 切换为暗黑模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red # 主色调
      accent: deep purple # 强调色调
      toggle:
        icon: material/weather-sunny
        name: 切换为暗黑模式

    # 切换为浅色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: red
      toggle:
        icon: material/weather-night
        name: 切换为浅色模式
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs #选项卡
    # - navigation.tabs.sticky #选项卡固定，滚动时还可见
    # - navigation.sections #章节视图，可以和tabs搭配使用
    - navigation.expand #展开侧边栏
    - navigation.prune
    - navigation.indexes # 点击文件夹显示index.md的内容
    - navigation.top # 回到顶部
    - toc.follow # 目录跟随
    - header.autohide # 滚动时隐藏顶部
    - navigation.footer # 底部导航，上下页
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    # 编辑和查看源码
    - content.action.edit
    - content.action.view
    - content.code.copy
edit_uri: "tree/main/docs/"
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - git-revision-date-localized:
    enable_creation_date: true
 - search


nav:
  - 主页: 'index.md'
  - 教程: 
    - PyTorch基础: 'tutorials/00_pytorch_fundamentals.md'
  - 练习: 
    - PyTorch基础: 'exercises/questions/00_pytorch_fundamentals_exercises.ipynb'
  - 答案: 
    - PyTorch基础: 'exercises/answers/00_pytorch_fundamentals_exercise_solutions.ipynb'


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YQisme
      name: github主页
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/244185393?spm_id_from=333.788.0.0
      name: b站主页
    - icon: fontawesome/solid/person
      link: https://eanyang7.com
      name: 个人主页

copyright: Copyright &copy; 2023 Ean Yang